### ISSUE TITLE
octane support

### ISSUE THREAD

**Issue by kaioken** [as-yakovenko/laravel-lighthouse-graphql-multi-schema#5]
Hi team, does this package support Octane? We’re running tests, but once we use swoole + octane, the requests are cached to the default schema.

Thanks

**Comment by kaioken** [comment]
@as-yakovenko that's awesome please do, I'll test it out right away and give any feedback, thanks

**Comment by as-yakovenko** [comment]
> [@as-yakovenko](https://github.com/as-yakovenko) that's awesome please do, I'll test it out right away and give any feedback, thanks

Hey! I’ve just pushed a PR that adds full Laravel Octane support by dynamically resolving the schema cache path per request.
Here’s the link: [(https://github.com/as-yakovenko/laravel-lighthouse-graphql-multi-schema/pull/6)](https://github.com/as-yakovenko/laravel-lighthouse-graphql-multi-schema/pull/6)

This PR refactors the cache layer to support Laravel Octane by resolving the schema cache path dynamically per request. It also makes the package fully stateless and compatible with long-lived workers.
**Note:** This is a temporary workaround until dynamic cache path support is available in Lighthouse core.

Please feel free to test it out and let me know if everything works on your side. Once confirmed, I’ll merge it into the main branch.

**Comment by FredPeal** [comment]
Hey! Thanks so much for the work you’re doing on this. I tested the branch from [PR #6](https://github.com/as-yakovenko/laravel-lighthouse-graphql-multi-schema/pull/6) with Laravel Octane, but unfortunately it didn’t work on my end.

If there’s any additional configuration I should set up, please let me know. Thanks again for your efforts!

**Comment by as-yakovenko** [comment]
> Hey! Thanks so much for the work you’re doing on this. I tested the branch from [PR #6](https://github.com/as-yakovenko/laravel-lighthouse-graphql-multi-schema/pull/6) with Laravel Octane, but unfortunately it didn’t work on my end.
> 
> If there’s any additional configuration I should set up, please let me know. Thanks again for your efforts!

Hi! Thanks for testing the previous version. I made changes for Octane compatibility.
The main problems were:
ASTCache was registered as singleton, causing request context to be cached across workers
The SchemaASTCache class was storing request references instead of resolving them dynamically.
I've pushed an updated version that:
Changes ASTCache registration from singleton to bind for fresh instances per request
Implements dynamic request resolution in SchemaASTCache to ensure correct schema context

Please let me know if this resolves the issue on your end!

**Comment by as-yakovenko** [comment]
@FredPeal 

Additional user recommendations:
Check cache folder permissions
Make sure cache paths are unique for each scheme
Clear all caches before testing
The fixes should resolve the issue with caching requests to the default scheme in the Octane environment.

**Comment by FredPeal** [comment]
Hey @as-yakovenko  , it’s me again. I tried again—deleted my vendor folder and reinstalled everything, cleared the cache and the cache folder, and even used Lighthouse’s command to clear the schema cache, but it still didn’t work.
I also copied the code from the PR you created directly into my codebase, and unfortunately, it still doesn’t work.

Not sure what I’m doing wrong 😔

**Comment by as-yakovenko** [comment]
@FredPeal 

Hey!
Thanks for the details! I’ve double-checked the Lighthouse internals and my package logic — everything should work as long as:
 - My service provider is loaded after the default LighthouseServiceProvider
 - No other package or your own code registers SchemaSourceProvider or ASTCache as a singleton
 - All caches are cleared after changes

To help you further, could you please share:
 - Show your config/app.php providers array (to check the order)
 - Your composer.json (Laravel, Lighthouse, Octane versions)
 - Add a debug field to your GraphQL schema that returns the current schema key (to see which schema is actually used per request)
 - Temporarily disable all other Lighthouse-related providers except mine and the default one
- The exact command you use to start Octane
 - Add a log line in SchemaASTCache::getCurrentCachePath() to see which cache path is used per request
 - Your config/lighthouse-multi-schema.php
 - The output of ls -la bootstrap/cache/ after making requests to different schemas
 - The contents of your storage/logs/laravel.log after making those requests (with APP_DEBUG=true)

 This will help me reproduce your setup and spot any hidden issues.
 Also, please check that you don’t override ASTCache or SchemaSourceProvider in your own service providers.

 Thank you!

**Comment by FredPeal** [comment]
Hi! 😊

I’ve been debugging the code and noticed that the SchemaASTCache is being executed, but only once. After investigating a bit, I realized this behavior is related to how Laravel Octane works.

Octane doesn’t fully reboot the framework on every request — instead, it keeps the container alive between requests. This means that any service binding that depends on app('request') will retain the original request object used when the worker first booted.

In the file [LighthouseMultiSchemaServiceProvider.php](https://github.com/as-yakovenko/laravel-lighthouse-graphql-multi-schema/blob/9c79662f30136b366def5c4ade3725b399987061/src/LighthouseMultiSchemaServiceProvider.php#L44), I saw that you’re doing:
```php
$app->make('request'
```
Would you mind testing if replacing that with the helper function request() works better? That helper is properly refreshed by Octane on each request, so it should resolve the issue.

Thanks again for all the great work you’re doing on this package! 🙌 Let me know if I can help further.

**Comment by kaioken** [comment]
@as-yakovenko So far, everything seems to be working well. Thanks!

One last question: what’s the best approach for versioning? Should I copy the same schema from one folder to another? Is there a way to avoid copying each file and instead link the old ones and add the new or modified methods?

**Comment by as-yakovenko** [comment]
@kaioken 
Hi!
Great to hear that everything is working well - thanks for testing!
**Regarding versioning your schemas:**
You don’t need to copy the entire schema for each version. The best approach is to split your schema into reusable parts (types, enums, inputs, queries, mutations, etc.) and use the `#import`  (supported by Lighthouse) to include shared files.
**For example, you can organize your /graphql directory like this:**
```
/graphql
├── models/                # Shared types, enums, inputs
│   ├── User.graphql
│   ├── Order.graphql
│   └── Product.graphql
├── v1/
│   ├── v1.graphql         # Entry point for v1, imports shared models and v1-specific queries/mutations
│   └── request/
│       ├── user_request.graphql
│       └── order_request.graphql
├── v2/
│   ├── v2.graphql         # Entry point for v2, can import the same models and only add/override what's new
│   └── request/
│       ├── user_request.graphql
│       └── order_request.graphql
```
In your entry file (**e.g., v2.graphql**):

```
#import ../models/*.graphql
#import ./request/*.graphql

# Scalars, Query, Mutation, etc.
```

This way, you only add or override what’s new in each version, and all unchanged types/fields are reused.
If you need to customize a type for a specific version, you can create a version-specific file and import it only in that version’s entry file.
**Summary:**
Use #import to share common schema parts between versions.
Only add or override files for new or changed functionality.
No need to copy unchanged files - just import them!
The `#import` approach is the most scalable and maintainable way to version your schemas, and is widely used in production projects.
